---
title: "PCA Example"
author: "Dan Veltri"
date: "9/9/2019"
output:
  html_document: default
---

```{r setup, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Iris Data Principal Components Analysis

This is a built-in data set for R from Fisher and Anderson. It contains four measurements (cols 1-4) for 50 samples each of three different iris spp. (col 5). Let's run PCA on the data and see if we can visualize view it in a 2D plot:

```{r iris-pca}
data('iris')
head(iris) # see what it looks like
iris.x = iris[,1:4] # measurements
iris.y = iris[,5] # our response labels

iris.pca = prcomp(iris.x, scale=TRUE, center=TRUE)
summary(iris.pca)
plot(iris.pca,main="Proportion of Variance for PCs 1-4",xlab="PCs 1-4")
```

It looks like the cumulative variance for PC1 and PC2 is greater than 95%. Let's use these to make our plot.
```{r iris-pca-2d-plot}
plot(iris.pca$x[,1], iris.pca$x[,2], col=iris.y, main="2D PCA Plot of Iris Data",xlab="PC1 (Variance 73%)",ylab="PC2 (Variance 23%)")
```

